name: Main Workflow

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo code
      uses: actions/checkout@v4

    - name: set up node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: set up the file application
      run: |
          git clone https://github.com/Grisha596/filebrowser.git
          cd filebrowser/frontend
          npm install
          npm run build
          cd ..
          go mod download
          go run main.go &

      - name: wait file browser
        run: |
          sudo apt-get install wait-for-it -y
          wait-for-it -h localhost -p 8080 -t 10

    - name: install dependencies
      run: npm install

    - name: run playwright tests
      run:  npx playwright install
            npm run test:e2e **/tests

    - name: Run Playwright tests with custom URL
      env:
      CUSTOM_SIGNUP_URL: 'https://grisha596.github.io/SoftwareTesting/htmlFIle/createUser.html'
      CUSTOM_SIGNUP_URL: 'https://grisha596.github.io/SoftwareTesting/htmlFIle/powerTrade_1.html '
      run: npx playwright test:e2e **/tests
      
