name: Main Workflow

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo code
      uses: actions/checkout@v4

    - name: set up node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: install dependencies
      run: npm install

    - name: run playwright tests
      run:  npx playwright install
            npm run test:e2e **/tests
      
